import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const styles = StyleSheet.create({
  panel: {
    flex: 1,
    backgroundColor: colors.background,
    paddingTop: 80,
    paddingBottom: 28,
  },
  inner: {
    paddingHorizontal: 20,
    gap: 20,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  title: {
    fontFamily: 'CabinetGrotesk-Bold',
    fontWeight: 600,
    fontSize: 35,
    color: colors.brown,
  },
  filterPanel: {
    position: 'absolute',
    left: 20,
    right: 20,
    zIndex: 10,
    borderRadius: 16,
    backgroundColor: colors.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
  },
  searchInput: {
    width: '100%',
    minHeight: 50,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: `${colors.brown}70`,
    backgroundColor: colors.white,
    paddingHorizontal: 14,
    fontFamily: 'Satoshi-Regular',
    fontSize: 14,
    color: colors.black,
  },
  error: {
    marginTop: 8,
    color: '#8b2a1b',
    fontFamily: 'Satoshi-Regular',
    fontSize: 12,
  },
  resultsCounter: {
    marginTop: 4,
    marginBottom: 6,
    color: colors.brownMid,
    fontFamily: 'Satoshi-Regular',
    fontSize: 12,
  },
  listContent: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 4,
    gap: 10,
  },
  listEmptyContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 12,
    justifyContent: 'center',
  },
  resultCard: {
    backgroundColor: colors.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: `${colors.brown}18`,
    paddingVertical: 12,
    paddingHorizontal: 12,
    gap: 6,
  },
  resultTitle: {
    fontFamily: 'CabinetGrotesk-Bold',
    fontSize: 18,
    color: colors.black,
  },
  resultMeta: {
    fontFamily: 'Satoshi-Bold',
    fontSize: 12,
    color: colors.salmon,
  },
  resultSnippet: {
    fontFamily: 'Satoshi-Regular',
    fontSize: 13,
    color: colors.brownMid,
  },
  resultActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  actionButton: {
    flex: 1,
  },
  emptyState: {
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 20,
  },
  emptyTitle: {
    fontFamily: 'CabinetGrotesk-Bold',
    fontSize: 22,
    color: colors.black,
    textAlign: 'center',
  },
  emptySubtitle: {
    fontFamily: 'Satoshi-Regular',
    fontSize: 14,
    color: colors.brownMid,
    textAlign: 'center',
  },
});
